### ISSUE TITLE
How to produce *.db and covariance files using JTI

### ISSUE THREAD

**Issue by YaCui** [gamazonlab/MR-JTI#2]
Hi,

The training example of JTI in GitHub(JTI.r) cannot produce *.db and covariance files which are required by PrediXcan/MetaXcan. Could you please describe more about this?

Thanks,
Ya

**Comment by zdangm** [comment]
Hi Ya,
I updated the script for the predixcan (https://github.com/gamazonlab/MR-JTI/tree/master/model_training/predixcan) which incorporates an option for generating .db file. The process from weight file to .db file is the same for predixcan and JTI. I hope that will be helpful.
Dan

**Comment by YaCui** [comment]
Thank you Dan!
